version: "3.9"

networks:
  django_simple_app:
    name: django_simple_app

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
    - .env
    networks:
      - django_simple_app

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    env_file:
    - .env
    ports:
      - "8004:8000"
    networks:
      - django_simple_app
    command: python manage.py runserver 0.0.0.0:8000
